# Generated by Django 4.2.14 on 2024-10-08 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("acquirer", models.CharField(max_length=50)),
                ("settle", models.BooleanField()),
                ("days_to_receive", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("fee", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
