# Generated by Django 4.2.14 on 2024-10-09 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmieAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("omie_id", models.BigIntegerField()),
                ("account_number", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_number",
        ),
        migrations.AlterField(
            model_name="account",
            name="acquirer",
            field=models.CharField(choices=[("PAGAR.ME", "Pagar.me")], max_length=50),
        ),
        migrations.AddField(
            model_name="account",
            name="omie_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.omieaccount",
            ),
        ),
    ]
