# Generated by Django 4.2.14 on 2024-10-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_omieaccount_remove_account_account_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="acquirer",
        ),
        migrations.RemoveField(
            model_name="account",
            name="omie_account",
        ),
        migrations.RemoveField(
            model_name="omieaccount",
            name="account_number",
        ),
        migrations.AddField(
            model_name="account",
            name="omie_account_destiny",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destiny",
                to="accounts.omieaccount",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="omie_account_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin",
                to="accounts.omieaccount",
            ),
        ),
    ]
