# Generated by Django 4.2.14 on 2024-10-09 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_omieaccount_remove_account_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cod_id_omie", models.IntegerField()),
                ("account_name", models.CharField(max_length=255)),
                ("tid", models.CharField(max_length=50)),
                ("invoice_number", models.CharField(max_length=50)),
                ("expected_value", models.FloatField()),
                ("fee", models.FloatField()),
                ("balance", models.FloatField()),
                ("expected_date", models.DateField()),
                ("accounts_receivable_note", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit"),
                            ("CREDIT", "Credit"),
                            ("PIX", "Pix"),
                        ],
                        max_length=50,
                    ),
                ),
                ("received_value", models.FloatField(blank=True, null=True)),
                ("value_difference", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("alert", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
