# Generated by Django 4.2.14 on 2024-10-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_transaction_invoice_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="alert",
            new_name="installment",
        ),
    ]
