# Generated by Django 4.2.14 on 2024-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_rename_alert_transaction_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="acquirer_fee",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
