# Generated by Django 4.2.14 on 2024-11-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transaction_acquirer_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="omie_fee_launched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="omie_receipt_releasead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="omie_value_transferred",
            field=models.BooleanField(default=False),
        ),
    ]
