# Generated by Django 4.2.14 on 2024-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_transaction_omie_fee_launched_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
