# Generated by Django 4.2.14 on 2024-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_transaction_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="project",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
