# Generated by Django 4.2.14 on 2025-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_department_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
