# Generated by Django 4.2.14 on 2024-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercard",
            name="card",
        ),
        migrations.RemoveField(
            model_name="usercard",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="cards",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="color",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="department",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="type",
        ),
        migrations.DeleteModel(
            name="Card",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="UserCard",
        ),
    ]
